apiVersion: v1
kind: Namespace
metadata:
  name: selfsigned-certs
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-certificate
  namespace: selfsigned-certs
spec:
  dnsNames:
    - example.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: selfsigned-issuer