apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSClusterTemplate
metadata:
  name: myfirst
spec:
  template:
    spec:
      patches:
      - name: region
        definitions:
          - selector:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
              kind: AWSClusterTemplate
              matchResources:
                infrastructureCluster: true
            jsonPatches:
              - op: add
                path: /spec/template/spec/region
                valueFrom:
                  variable: region
      - name: sshKeyName
        definitions:
          - selector:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
              kind: AWSClusterTemplate
              matchResources:
                infrastructureCluster: true
            jsonPatches:
              - op: add
                path: /spec/template/spec/sshKeyName
                valueFrom:
                  variable: sshKeyName
          - selector:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
              kind: AWSMachineTemplate
              matchResources:
                controlPlane: true
                machineDeploymentClass:
                  names:
                    - default-worker
            jsonPatches:
              - op: add
                path: /spec/template/spec/sshKeyName
                valueFrom:
                  variable: sshKeyName
      - name: controlPlaneMachineType
        definitions:
          - selector:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
              kind: AWSMachineTemplate
              matchResources:
                controlPlane: true
            jsonPatches:
              - op: replace
                path: /spec/template/spec/instanceType
                valueFrom:
                  variable: controlPlaneMachineType
      - name: workerMachineType
        definitions:
          - selector:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
              kind: AWSMachineTemplate
              matchResources:
                machineDeploymentClass:
                  names:
                    - default-worker
            jsonPatches:
              - op: replace
                path: /spec/template/spec/instanceType
                valueFrom:
                  variable: workerMachineType
      variables:
      - name: region
        required: true
        schema:
          openAPIV3Schema:
            type: string
            default: us-east-1
      - name: sshKeyName
        required: true
        schema:
          openAPIV3Schema:
            type: string
            default: default
      - name: controlPlaneMachineType
        required: true
        schema:
          openAPIV3Schema:
            type: string
            default: t3.large
      - name: workerMachineType
        required: true
        schema:
          openAPIV3Schema:
            type: string
            default: t3.large
  
---
kind: KubeadmControlPlaneTemplate
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
metadata:
  name: myfirst-control-plane
spec:
  template:
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          apiServer:
            extraArgs:
              cloud-provider: aws
          controllerManager:
            extraArgs:
              cloud-provider: aws
        initConfiguration:
          nodeRegistration:
            name: '{{ ds.meta_data.local_hostname }}'
            kubeletExtraArgs:
              cloud-provider: aws
        joinConfiguration:
          nodeRegistration:
            name: '{{ ds.meta_data.local_hostname }}'
            kubeletExtraArgs:
              cloud-provider: aws
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: myfirst-control-plane
spec:
  template:
    spec:
      # instanceType is a required field (OpenAPI schema).
      instanceType: REPLACEME
      iamInstanceProfile: "control-plane.cluster-api-provider-aws.sigs.k8s.io"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: myfirst-worker-machinetemplate
spec:
  template:
    spec:
      # instanceType is a required field (OpenAPI schema).
      instanceType: REPLACEME
      iamInstanceProfile: "nodes.cluster-api-provider-aws.sigs.k8s.io"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: "myfirst-worker-bootstraptemplate"
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: '{{ ds.meta_data.local_hostname }}'
          kubeletExtraArgs:
            cloud-provider: aws